### ISSUE TITLE
Devel: b0 error when trying to run the tests

### ISSUE THREAD

**Issue by panglesd** [dbuenzli/cmarkit#12]
I'm trying to add support for some other extensions[^1].

[^1]:  More specifically [fenced divs and bracketed spans from pandoc](https://pandoc.org/MANUAL.html#divs-and-spans). I need them in another project, but I'd be happy to upstream them if you want!

DEVEL.md suggests to use `b0 -- expect` (or `b0 -- test_expect` in older commits).
However, I could not make this to work. I tried several combinations for the versions of b0 (master, last released version, something in between) and cmarkit (main, 0.2, 0.1), but I always get an error...

<details>
<summary>Different errors</summary>

- cmarkit at `main`, `b0` pinned at `master`
```
$ b0 -- expect   
[FAIL] [ocamlopt][2]: (b0 file log --id 19)
File "-", line 1, characters 9-26:
Error: Unbound value B0_def.Scope.root

b0: Error: Could not compile B0 file /home/panglesd/code/cmarkit/B0.ml
```
- `cmarkit` at `main`, `b0` at `0.0.5` (last released version)
```
$ b0 -- expect 
[FAIL] [ocamlopt][2]: (b0 file log --id 21)
File "/home/panglesd/code/cmarkit/B0.ml", line 60, characters 30-33:
Error: Unbound value arg

b0: [ERROR] Could not compile B0 file /home/panglesd/code/cmarkit/B0.ml
```
- `cmarkit` at `0.2.0`, `b0` at `0.0.5`
```
$ b0 -- test_expect
[FAIL] [ocamlopt][2]: (b0 file log --id 21)
File "-", line 1, characters 9-31:
Error: Unbound value B0_def.Scope.open_root

b0: [ERROR] Could not compile B0 file /home/panglesd/code/cmarkit/B0.ml
```
- `cmarkit` at `0.2.0`, `b0` at `master`
```
$ b0 -- test_expect                                           
[FAIL] [ocamlopt][2]: (b0 file log --id 19)
File "/home/panglesd/code/cmarkit/B0.ml", line 41, characters 2-13:
Error: Unbound module B0_cmdlet

b0: Error: Could not compile B0 file /home/panglesd/code/cmarkit/B0.ml
```
- I also tried some b0 commits in between `0.0.5` and `master`, without success...
```
File "-", line 1, characters 9-31:
Error: Unbound value B0_def.Scope.open_root
```
```
[FAIL] [ocamlopt][2]: (b0 file log --id 19)
File "/home/panglesd/code/cmarkit/B0.ml", line 109, characters 2-45:
Error: This expression has type unit but an expression was expected of type
         ('a, string) result
```

</details>

Could you provide some guidance on how to setup a development environment?

Thanks a lot! (And thanks for maintaining this!)

**Comment by dbuenzli** [comment]
Yes sorry `b0` got some work, I pushed both `b0` and `cmarkit` that should work now. Tell me if it does not.

> 1. More specifically [fenced divs and bracketed spans from pandoc](https://pandoc.org/MANUAL.html#divs-and-spans). I need them in another project, but I'd be happy to upstream them if you want! [↩](#user-content-fnref-1-1ad0b6f0d56ca860dfd81ae01809e1c0)

Do you need to support this exact syntax ? I'm not especially keen on these. If anything I would rather have [this](https://talk.commonmark.org/t/anchors-and-tapping-into-the-expressiveness-of-undefined-shortcut-reference-links/4011/2).

Also note that you can easily do generalized spans with references resolvers. I can give you some code would you need to.

**Comment by panglesd** [comment]
> Yes sorry b0 got some work, I pushed both b0 and cmarkit that should work now. Tell me if it does not.

Thanks for the quick reply, I can confirm it works perfectly now :)

> Do you need to support this exact syntax ? [...] If anything I would rather have [this](https://talk.commonmark.org/t/anchors-and-tapping-into-the-expressiveness-of-undefined-shortcut-reference-links/4011/2).

I'm still clearly in the "experimentation" phase, so there is nothing exact.
The linked syntax looks really good to give `id`s to blocks, but it does not allow to group multiple blocks in one block...
In particular, I'd like to use some kind of css framework to give more control on how the output is rendered. Eg, I'd like it to be easy to define a multiple-column layout:
```
::: columns ::
:::: column ::
a paragraph
::::
:::: column ::
another one
::::
:::
```
It's not perfect, but OK, and at least it's not new (in the sense that it was introduced by pandoc).

**Comment by dbuenzli** [comment]
I see, just a few suggestions.

> In particular, I'd like to use some kind of css framework to give more control on how the output is rendered. Eg, I'd like it to be easy to define a multiple-column layout:

Then I'm not really sure that's the right level to solve this problem, the idea of commonmark is plain text readability (see the philosophy [here](https://spec.commonmark.org/0.30/#what-is-markdown-)). 

But if you really want to do that in the commonmark document itself then I don't think you really get much out of that extension I think I would rather simply use [raw html blocks](https://spec.commonmark.org/0.30/#html-blocks) for that. Also if you can properly id or classify paragraphs then you can likely arbitrarily relayout them via CSS grid.
