### ISSUE TITLE
Unexpected `Block_line.list_of_string` output

### ISSUE THREAD

**Issue by 3Rafal** [dbuenzli/cmarkit#7]
When using function `list_of_string`, I've found out that it copies whole string into a first node:
```
utop # Block_line.list_of_string "a\nb\nc\n";;
- : Block_line.t list =
[("a\nb\nc\n", <abstr>); ("b", <abstr>); ("c", <abstr>); ("", <abstr>)]
```

I'd expect result to be `[("a", <abstr>); ("b", <abstr>); ("c", <abstr>); ("", <abstr>)]`. It would be consistent with implementation of `tight_list_of_string`:
```
utop # Block_line.tight_list_of_string "a\nb\nc\n";;
- : Block_line.tight list =
[("", ("a", <abstr>)); ("", ("b", <abstr>)); ("", ("c", <abstr>));
 ("", ("", <abstr>))]
```

**Comment by dbuenzli** [comment]
Fixed by f2215cbc0f291e104b6fc. Thanks @3Rafal.

**Comment by dbuenzli** [comment]
My suggestion didn't work, switched back to your initial proposal in b20bdae5dbf3a4b50e1

**Comment by dbuenzli** [comment]
Release on the way https://github.com/ocaml/opam-repository/pull/23781
