### ISSUE TITLE
Default value of `List_item.make`'s `after_marker` param

### ISSUE THREAD

**Issue by 3Rafal** [dbuenzli/cmarkit#9]
Currently, the default value of `after_marker` is set to 0:
https://github.com/dbuenzli/cmarkit/blob/b20bdae5dbf3a4b50e150562eb8194a626d05271/src/cmarkit.ml#LL588C46-L588C46

This means that by default, the list will be rendered to:
```
-first item
-second item
-third item
```
This will not be rendered as correct CommonMark list.

All list examples in CommonMark spec have one space after marker:
https://spec.commonmark.org/0.30/#lists

Should we change the default value to 1, so that it's more intuitive and works by default?

**Comment by dbuenzli** [comment]
Obviously! Thanks for the report.
